[[replacements]]
# \ (行末) -> \\
pattern = '\\$'
to = '\\\\'

[[replacements]]
pattern = '<->'
to = '\leftrightarrow'

[[replacements]]
pattern = '=>'
to = '\Rightarrow'

[[replacements]]
pattern = '->'
to = '\rightarrow'

[[replacements]]
pattern = '<-'
to = '\leftarrow'

[[replacements]]
pattern = '<='
to = '\leq'

[[replacements]]
pattern = '>='
to = '\geq'

[[replacements]]
pattern = '!='
to = '\neq'

[[replacements]]
pattern = '\.\.\.'
to = '\ldots'

[[replacements]]
pattern = '\*'
to = '\cdot'

[[replacements]]
pattern = '\btimes\b'
to = '\times'

[[replacements]]
pattern = '><'
to = '\times'
